#!/usr/bin/env bash
# lib/edge_cases.sh — edge case & stress test fixtures
# Sourced by generate.sh; uses helpers from lib/helpers.sh.

RES="$DEFAULT_RESOLUTION"
FPS="$DEFAULT_FPS"
CRF="$DEFAULT_CRF"
ABR="$DEFAULT_AUDIO_BITRATE"

_ec_enabled() { fixture_enabled edge_cases "$1"; }

if _ec_enabled very_short; then
  dur=$(fixture_get edge_cases very_short duration)
  ff very_short \
    -f lavfi -i "$(video_src "$RES" "$FPS" "$dur")" \
    -f lavfi -i "$(audio_src "$dur")" \
    -c:v libx264 -crf "$CRF" \
    -c:a aac -b:a "$ABR" \
    -t "$dur"
fi

if _ec_enabled long_2hr; then
  dur=$(fixture_get edge_cases long_2hr duration)
  crf=$(fixture_get edge_cases long_2hr crf)
  abr=$(fixture_get edge_cases long_2hr audio_bitrate)
  # Use 1fps and low-res to keep file size manageable
  ff long_2hr \
    -f lavfi -i "$(video_src "1280x720" 1 "$dur")" \
    -f lavfi -i "$(audio_src "$dur")" \
    -c:v libx264 -crf "$crf" \
    -c:a aac -b:a "$abr" \
    -t "$dur"
fi

if _ec_enabled truncated; then
  # Depends on h264_high being generated by codecs category.
  SRC_FILE="${OUTPUT_DIR}/h264_high.${EXT}"
  if [[ -f "$SRC_FILE" ]]; then
    log "→ truncated"
    dd if="$SRC_FILE" of="${OUTPUT_DIR}/truncated.${EXT}" bs=1024 count=10 2>/dev/null
    log "  OK  →  ${OUTPUT_DIR}/truncated.${EXT}"
  else
    log "  SKIP truncated (h264_high.${EXT} not found — run codecs category first)"
  fi
fi

if _ec_enabled bframes; then
  crf=$(fixture_get edge_cases bframes crf)
  dur="$DEFAULT_DURATION"
  ff bframes \
    -f lavfi -i "$(video_src "$RES" "$FPS" "$dur")" \
    -f lavfi -i "$(audio_src "$dur")" \
    -c:v libx264 -crf "$crf" -bf 4 -b_strategy 2 \
    -c:a aac -b:a "$ABR" \
    -t "$dur"
fi

if _ec_enabled many_fragments; then
  dur="$DEFAULT_DURATION"
  ff many_fragments \
    -f lavfi -i "$(video_src "$RES" "$FPS" "$dur")" \
    -f lavfi -i "$(audio_src "$dur")" \
    -c:v libx264 -crf "$CRF" \
    -c:a aac -b:a "$ABR" \
    -movflags frag_keyframe+empty_moov+default_base_moof \
    -frag_duration 500000 \
    -t "$dur"
fi
